<script src="{{asset('assets/js/jquery-3.2.1.min.js')}}"></script>
<script src="{{asset('assets/js/pre-loader.js')}}"> </script>
<script src="{{asset('assets/bootstrap/js/popper.min.js')}}"></script>
<script src="{{asset('assets/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/parallaxie.js')}}"></script>
<script src="{{asset('assets/js/TweenMax.min.js')}}"></script>
<script src="{{asset('assets/js/jquery.wavify.js')}}"></script>
<script src="{{asset('assets/wow/wow.min.js')}}"></script>
<script src="{{asset('assets/js/main.js')}}"></script>
